fsprojects/FSharp.Data.SqlClient

src/SqlClient.Tests/Ado.fsx, src/SqlClient.Tests/ConnectionStrings.fs, src/SqlClient.Tests/OptionalParamsTests.fs, src/SqlClient.Tests/ProgrammabilityTests.fs, src/SqlClient.Tests/ResultTypeTests.fs, src/SqlClient.Tests/Schema.fsx, src/SqlClient.Tests/SpatialTypesTests.fs, src/SqlClient.Tests/SqlClient.Tests.fsproj, src/SqlClient.Tests/SqlClientExtensionsTests.fs, src/SqlClient.Tests/SqlCommand.fsx, src/SqlClient.Tests/SqlEnumTests.fs, src/SqlClient.Tests/SqlProgrammability.fsx, src/SqlClient.Tests/TVPTests.fs, src/SqlClient.Tests/TransactionTests.fs, src/SqlClient.Tests/TypeProviderTest.fs, src/SqlClient.Tests/app.config
I think it's helpful for development when configuration is a bit different than default one, just two places to changes:
app.config
ConnectionStrings.fs
instead of changing connection strings in most of the test files.
=> minor refactoring of duplicated string literals used for connection strings

src/SqlClient.Samples/WebApi.Controllers/DataAccess.fs, src/SqlClient.Tests/ConfigurationTest.fs, src/SqlClient/Configuration.fs
Fixes #110 
After a discussion in PR #112 we decided to not remove resolutionFolder because it helps when you expect your code to be `#load`ed from other folders. 
This PR just fixes the issue where you need to reopen the solution for changes to .sql files to be picked up.
=> Make FileSystemWatcher more reliable

src/SqlClient.Tests/SqlEnumTests.fs, src/SqlClient/SqlEnumProvider.fs
In SqlEnumProvider.fs when the query returns more than 2 columns, getValue was skipping first value AND first type in the tuple type definition, it should only skip first value but keep the type definition intact.
Added a basic test checking provided type exposes correct values.
I intend to use the feature soon, I would appreciate if we could have an updated nuget package for testing.
=> Fix for #190: SqlEnumProvider fails to compile when query has more than 2 fields.

docs/content/output.fsx, src/SqlClient.Tests/DataTablesTests.fs, src/SqlClient/DesignTime.fs, src/SqlClient/SqlClientProvider.fs, src/SqlClient/SqlCommandProvider.fs
I think this is minimal firs step to get this feature done, I'm open for suggestions if you want me to address any concern.
I'd like to work on removing code duplication between `SqlProgrammabilityProvider` and `SqlCommandProvider` but I wonder if this is not already being done in V2 branch and I think this should be a separate PR.
Detail of actual changes to make the feature work:
* add DesignTime.GetDataTableType to encapsulate creation of Table type (might make the type name a parameter in later consolidation, see note)
* when ResultType.DataTable is used, add the ProvidedType (which was already of DataTable type) as a member to SqlCommandProvider provided type
* add a simple unit test which shows that we can specify the type explicitly (I've removed importing ProgrammabilityTest as it …
=> Expose an additional Table type when ResultType.DataTable is used

docs/content/data modification.fsx, src/SqlClient.Tests/DataTablesTests.fs, src/SqlClient/DesignTime.fs, src/SqlClient/QuotationsFactory.fs, src/SqlClient/SqlClientProvider.fs
for each column of the result set, a get property named after the column name is attached to `DataTable.Columns`:
```fsharp
let table = Command.Execute()
let column1 : System.Data.DataColumn = table.Columns.column1
```
Edit: the part bellow not part of this PR anymore:
```fsharp
member this.GetValue (row: DataRowType) : ColumnType
member this.SetValue (row: DataRowType) (value: ColumnType) : unit
```
```fsharp
let value : int = column1.GetValue(table.Rows.[0])
column1.ReadOnly <- false
column1.SetValue(table.Rows.[0], value + 1)
```
=> Expose DataColumn properties on DataColumnCollection

src/SqlClient/SqlClientProvider.fs
Added obosolete attribute on Table.NameOfColumnColumn properties with a message pointing to the new property.
=> Make Table.NameOfColumnColumn property obsolete

docs/content/index.fsx
In the first paragraph of the front page!
=> Just a typo fix in the documentation

src/SqlClient.Tests/DataTablesTests.fs, src/SqlClient/DesignTime.fs, src/SqlClient/SqlClientProvider.fs
Allow to recover typed datatable from typed datarow instance via `.Table` property.
=> Convenience DataRow.Table property should point to typed table

docs/output/content/style.css, docs/tools/templates/template.cshtml
Fixes #182 
Make JS and CSS includes relative to the current protocol instead of fixing to http which causes browsers to not load the content due to insecure content.
=> Fix docs site on https

src/SqlClient/SingleRootTypeProvider.fs
based on investigation from @mrinaldi in #241 and suggestion from @dsevastianov to clear the cache instead of disposing it.
I confirm that in my case it doesn't crash anymore.
=> fix for #240

src/SqlClient.Tests/ProgrammabilityTests.fs, src/SqlClient/DesignTime.fs, src/SqlClient/SqlClientProvider.fs, src/SqlClient/SqlCommandProvider.fs
* factorize common logic handling addition of inner types (for record and table types)
* fix XML documentation for SqlProgrammabilityProvider
* add one test checking the table return type on a function call
I'm looking for ideas to add more tests.
It addresses what I initially understood from #257 which is pointing about mixed-up documentation about `ResultType`
I intend to use `ResultType.DataTable` in work codebase and I'll need to define `.Table` members
Note: I have issues locally to build most of the tests, they expect something different than no parameter at commands' constructor call sites, I haven't been able to compile run all other tests, can somebody confirm the issue?
=> Add handling of ResultType static parameter for SqlProgrammabilityProvider

src/SqlClient.Tests/DataTablesTests.fs, src/SqlClient/DesignTime.fs
This PR provides those members which were discussed in #215
``` fsharp
member this.GetValue (row: DataRowType) : ColumnType
member this.SetValue (row: DataRowType) (value: ColumnType) : unit
```
allowing such code as shown bellow; useful when the column is coming from an expression in the SQL which makes that there is no setter on provided properties.
``` fsharp
let value : int = column1.GetValue(table.Rows.[0])
column1.ReadOnly <- false
column1.SetValue(table.Rows.[0], value + 1)
```
=> Expose custom getter/setter methods on provided DataColumn properties

src/SqlClient.Tests/SqlClient.Tests.NET40/App.config, src/SqlClient.Tests/SqlClient.Tests.NET40/SqlClient.Tests.NET40.fsproj, src/SqlClient/DesignTime.fs, src/SqlClient/SqlClient.fsproj, src/SqlClient/SqlClientExtensions.fs, src/SqlClient/packages.config
support newer Sql Server T-Sql versions
For example queries with hints like : 
select * from Table
option ( use hint('enable_parallel_plan_preference'))
=> upgrade tsql parser version

src/SqlClient.Tests/DataTablesTests.fs, src/SqlClient/DataTable.fs, src/SqlClient/DesignTime.fs, src/SqlClient/SqlClientProvider.fs
This addresses #228.
Regarding the constructor code quotation, I've tried to factorize the code within the quotation but had issues to make this compile or work at design time, I moved most of the constructor body into `setupTableFromSerializedColumns` function called from the quotation.
=> Enable typed data table constructor to initialize an empty datatable with the expected columns.

src/SqlClient.DesignTime/SqlClientExtensions.fs, tests/SqlClient.Tests/TVPTests.fs, tests/SqlClient.Tests/extensions.sql
This is an update to #313 to fix #312.
=> Fix exception when using TVP parameter with fixed length string

src/SqlClient.DesignTime/ProvidedTypesCache.fs, src/SqlClient.DesignTime/SingleRootTypeProvider.fs
This will prevent Visual Studio from caching created types until VS is restarted or until project is unloaded and reloaded.
=> Invalidate SqlFile type when referenced SQL file is modified.

.gitignore, src/SqlClient.DesignTime/DesignTime.fs, src/SqlClient/Shared.fs, tests/SqlClient.Tests/ProgrammabilityTests.fs, tests/SqlClient.Tests/extensions.sql
This is a fix for non primitive out types in stored procedures.
I had a case with a output parameter of type Guid, the type provider could not use the Expr.Value(Activator.CreateInstance(…)) since it can do so only for primive types.
In the case of a non primite type, we use Expr.DefaultValue(t) which calls the default ctor.
The change in SetRef<'t> was necessary to set the output value to default<'t> when the parameter value is actually DBNull. This raise the question of actually making it optional…
=> Fix: non primitive out types

src/SqlClient/DataTable.fs, tests/SqlClient.Tests/DataTablesTests.fs, tests/SqlClient.Tests/extensions.sql
I think this is a pretty simple implementation for Issue #324.
I ended up putting in kind of a goofy test with a trigger since there's no direct access to SQL in that scenario.  Since it's a timeout test, I put in the 'Skip' flag on the test to match other timeout tests I saw.
=> Allow timeout on data table Update commands

src/SqlClient/ISqlCommand.fs, tests/SqlClient.Tests/CreateCommand.fs, tests/SqlClient.Tests/TypeProviderTest.fs
Fixes some annoying issues with the query generated by `ToTraceString`:
- `tinyint` and `xml` data formats do have a width specifier (1 and -1 respectively), but MSSQL doesn't recognize it in input. This PR adds exceptions.
- Parameter values in trace strings aren't escaped if they contain `'`. This PR doubles any single quotes in parameter values.
- Date/time parameters are printed in local formats, which may or may not be accepted by the server. This PR changes them to ISO8601 format which should work regardless of MSSQL configs. _Potentially_ breaking change if someone out there is parsing trace strings using `.ParseExact`.
=> Improve trace string

docs/content/dynamic local db.fsx
Closes #356 
I wasn't able to generate the docs; there were warnings errors all over the place when executing the build script. I don't think they were related to my changes. Feel free to test yourselves. :)
=> Improve dynamic DB docs

docs/content/dynamic local db.fsx
=> Fix typo and formatting in dynamic DB docs

src/SqlClient/ISqlCommand.fs, tests/SqlClient.Tests/CreateCommand.fs, tests/SqlClient.Tests/TypeProviderTest.fs
Thanks for merging the previous PR. I've addressed some more issues with the commands created by `ToTraceString`:
- String parameters are now also preceded by `N` to correctly escape Unicode characters 
- Numeric parameters are printed in culture-invariant format
- The ISO-8601 timestamp format works for `datetimeoffset` and `datetime2` fields, but for older  `datetime` fields it's not guaranteed to work and is best encoded as `yyyy-MM-ddTHH:mm:ss.fff`  (see [this](https://dba.stackexchange.com/questions/63641/understanding-datetime-formats-in-sql-server) SO answer)
- Decimal parameters are declared with precision and scale. This prevents them from being silently rounded to integers
- Nulls are printed as literal NULLs
=> More tracestring improvements

docs/content/dynamic local db.fsx
Adding parameter `-d "$DbName"` so the script does not need to include `USE` command.
If source database has a different name `USE` command will fail and objects will be created in master.
=> Adding parameter -d to sqlcmd

src/SqlClient.DesignTime/SqlClient.DesignTime.fsproj, src/SqlClient/Shared.fs, src/SqlClient/SqlClient.fsproj
Not used at runtime and saves compile time.
=> remove type provider SDK files from SqlClient.fsproj

src/SqlClient/ISqlCommand.fs
this member is legitly used publicly and shouldn't be under Internals, will be fixed in next 2.1 beta.
=> move ISqlCommand outside of Internals namespace
